Convex hull of intersections: G:/GIT/home-assignment-szekely-tibi/ConvexHullOfIntersections/ConvexHullOfIntersections.cpp File Reference
ConvexHullOfIntersections.cpp File Reference
#include "Set.h"
#include "IntersectionCalculator.h"
#include <iostream>
#include <sstream>
Functions
void generateStressTest (int numPrimitives=1000)
int main ()
Variables
Set theSet
Function Documentation
generateStressTest()
void generateStressTest (int numPrimitives = 1000)
{
     ofstream outfile;
     outfile.open("stressTest.dat");
     outfile << to_string(numPrimitives) << endl;
     const int width = 100;
     const int height = 100;
     const int maxRadius = 50;
     for (int i = 0; i < numPrimitives; i++) {
         stringstream ss;
         int rPrim = rand() % 2;
         switch (rPrim) {
             case 0:
             {
                 int rX = rand() % width;
                 int rY = rand() % height;
                 int rR = rand() % maxRadius;
                 ss << "C " << rX << " " << rY << " " << rR;
             }
             break;
             case 1:
             {
                 int rX0 = rand() % width;
                 int rY0 = rand() % height;
                 int rX1 = rand() % width;
                 int rY1 = rand() % height;
                 ss << "L " << rX0 << " " << rY0 << " " << rX1 << " " << rY1;
             }
             break;
         }
         outfile << ss.str() << endl;
     }
     outfile.close();
 }
main()
int main ()
 {
     std::cout << "Convex Hull Of Intersections!\n";
     std::cout << "-----------------------------\n";
     //generateStressTest();
     if (IntersectionCalculator::test()) {
         theSet.getPrimitives();
         theSet.writeOutPrimitives(true);
         theSet.calcIntersections();
         theSet.writeOutPoints(true);
         //theSet.findHullPoints();
         theSet.findConvexHullJarvis();
         theSet.writeOutHullPoints(true);
         theSet.calcAreaOfTheConvexHull();
     }
     else
         cout << "Error! The algorithm test is unsucessfull.";
 }
References Set::calcAreaOfTheConvexHull(), Set::calcIntersections(), Set::findConvexHullJarvis(), Set::getPrimitives(), IntersectionCalculator::test(), theSet, Set::writeOutHullPoints(), Set::writeOutPoints(), and Set::writeOutPrimitives().
Variable Documentation
theSet
Set theSet
Referenced by main().