Convex hull of intersections: Set Class Reference
Set Class Reference
#include <Set.h>
Public Member Functions
Set ()
~Set ()
void getPrimitives (bool fromFile=false)
void writeOutPoints (bool toFile=false)
void writeOutHullPoints (bool toFile=false)
void writeOutPrimitives (bool toFile=false)
void calcIntersections ()
void findHullPoints ()
void findConvexHullJarvis ()
double calcAreaOfTheConvexHull ()
vector< Point > intersect (const Primitive *p1, const Primitive *p2)
Static Public Member Functions
static constexpr short perm (const char t1, const char t2)
Public Attributes
vector< Primitive * > primitives
vector< Point > points
vector< Point > hullPoints
ofstream ofile
Static Public Attributes
static Point debugPoint
Detailed Description
Constructor & Destructor Documentation
Set()
Set::Set ()
         {
     ofile.open("output.dat");
 }
~Set()
Set::~Set ()
           {
     for (int i = 0; i < primitives.size(); i++) {
         delete primitives[i];
     }
     ofile.close();
 }
Member Function Documentation
calcAreaOfTheConvexHull()
double Set::calcAreaOfTheConvexHull ()
{
     double area = 0;
     int j = hullPoints.size() - 1;
     for (int i = 0; i < hullPoints.size(); i++) {
         const Point &pi = hullPoints[i];
         const Point& pj = hullPoints[j];
         area += (pj.x + pi.x) * (pj.y - pi.y);
         j = i;
     }
     double res = abs(area / 2.0);
     cout << res;
     ofile << res << endl;
     return area;
 }
References Point::x, and Point::y.
Referenced by main().
calcIntersections()
void Set::calcIntersections ()
{
     points.clear();
     for (int i = 0; i < primitives.size(); i++) {
         for (int j = i; j < primitives.size(); j++) {
             if (i != j) {
                 Primitive *p1 = primitives[i];
                 Primitive *p2 = primitives[j];
                 if (p1 != p2) {
                     vector<Point> is = intersect(p1, p2);
                     points.insert(points.end(), is.begin(), is.end());
                 }
             }
         }
     }
 }
Referenced by main().
findConvexHullJarvis()
void Set::findConvexHullJarvis ()
{
     int n = points.size();
     if (n < 3)
         return;
     hullPoints.clear();
     // Find the leftmost point
     int l = 0;
     for (int i = 1; i < n; i++)
         if (points[i].x < points[l].x)
             l = i;
     // Start from leftmost point, keep moving counterclockwise until reach the start point again.
     // This loop runs O(h) times where h is number of points in result or output.
     int p = l, q;
     do
     {
         // Add current point to result
         hullPoints.push_back(points[p]);
         // Search for a point 'q' such that orientation(p, x, q) is counterclockwise for all points 'x'.
         // The idea is to keep track of last visited most counterclock-wise point in q. If any point 'i' is more counterclock-wise than q, then update q.
         q = (p + 1) % n;
         for (int i = 0; i < n; i++)
         {
             // If i is more counterclockwise than current q, then update q
             if (orientation(points[p], points[i], points[q]) == 2)
                 q = i;
         }
         // Now q is the most counterclockwise with respect to p. Set p as q for next iteration,  so that q is added to result 'hull'
         p = q;
     } while (p != l); // While we don't come to first point
 }
Referenced by main().
findHullPoints()
void Set::findHullPoints ()
{
     if (points.size() < 2)
         return;
     hullPoints.clear();
     MemberType minY = points[0].y;
     int min = 0;
     for (int i = 1; i < points.size(); i++) {
                 MemberType y = points[i].y;
         if (y <= minY){
             if (points[i].x < points[min].x) {
                 minY = points[i].y;
                 min = i;
             }
         }
     }
     Point temp = points[0];          // SWAP
     points[0] = points[min];
     points[min] = temp;
     p0 = points[0];
         std::qsort(&points[1], points.size() - 1, sizeof(Point), Set::comparePoints);
     size_t arrSize = 1;
     for (size_t i = 1; i < points.size(); i++) {
     //  if (points[i] == debugPoint || points[i+1] == debugPoint)
     //      cout << "!!!! \n";
         while (i < points.size()-1 && direction(p0, points[i], points[i + 1]) == 0)
             i++;
         points[arrSize] = points[i];
         arrSize++;
     }
     if (arrSize < 3)
         return;
     stack<Point> stk;
     //if (points[0] == debugPoint || points[1] == debugPoint || points[0] == debugPoint)
     //  cout << "!!!!!\n";
     stk.push(points[0]);
     stk.push(points[1]);
     stk.push(points[2]);
     for (int i = 3; i < arrSize; i++) {
         while (direction(secondTop(stk), stk.top(), points[i]) != 2)
             stk.pop();
         stk.push(points[i]);
     }
     while (!stk.empty()) {
         hullPoints.push_back(stk.top());    //add points from stack
         stk.pop();
     }
 }
References direction().
getPrimitives()
void Set::getPrimitives (bool fromFile = false)
{
     ifstream infile;
     int numPrimitives;
 //  infile.open("stressTest.dat");
     infile.open("test.dat");
     if (fromFile) {
         infile >> numPrimitives;
         for (int i = 0; i < numPrimitives; i++) {
             char pType;
             infile >> pType;
             if (pType == 'L') {
                 long x0, y0, x1, y1;
                 infile >> x0;
                 infile >> y0;
                 infile >> x1;
                 infile >> y1;
                 Line* l = new Line(x0, y0, x1, y1);
                 primitives.push_back(l);
             }
             else if (pType == 'C') {
                 long x, y, r;
                 infile >> x;
                 infile >> y;
                 infile >> r;
                 Circle* c = new Circle(x, y, r);
                 primitives.push_back(c);
             }
         }
         infile.close();
     }
     else {
         cin >> numPrimitives;
         for (int i = 0; i < numPrimitives; i++) {
             char pType;
             cin >> pType;
             if (pType == 'L') {
                 long x0, y0, x1, y1;
                 cin >> x0;
                 cin >> y0;
                 cin >> x1;
                 cin >> y1;
                 Line *l = new Line(x0, y0, x1, y1);
                 primitives.push_back(l);
             }
             else if (pType == 'C') {
                 long x, y, r;
                 cin >> x;
                 cin >> y;
                 cin >> r;
                 Circle *c = new Circle(x, y, r);
                 primitives.push_back(c);
             }
         }
     }
     points.reserve(size_t(numPrimitives) * size_t(numPrimitives) * 2); // my guess
 }
Referenced by main().
intersect()
vector< Point > Set::intersect (const Primitive * p1, const Primitive * p2)
{
     vector<Point> pv;
     short p = perm(p1->t, p2->t);
     switch (p) {
         case perm('L', 'L'):
             // Line - Line intersection
             IntersectionCalculator::intersect((Line*)p1, (Line*)p2, pv);
             break;
         case perm('L', 'C'):
             // Line - Circle intersection
             IntersectionCalculator::intersect((Line*)p1, (Circle*)p2, pv);
             break;
         case perm('C', 'L'):
             // Line - Circle intersection
                 IntersectionCalculator::intersect((Line*)p2, (Circle*)p1, pv);
             break;
         case perm('C', 'C'):
             // Circle - Circle intersection
             IntersectionCalculator::intersect((Circle*)p1, (Circle*)p2, pv);
             break;
     }
     return pv;
 }
References IntersectionCalculator::intersect(), and Primitive::t.
perm()
static constexpr short Set::perm (const char t1, const char t2) inline static constexpr
     {
         return (t1 << 8) | t2;
     }
writeOutHullPoints()
void Set::writeOutHullPoints (bool toFile = false)
{
     if (toFile) {
         ofile << hullPoints.size() << endl;
         ofile << "yellow" << endl;
     }
     cout << hullPoints.size() << endl;
     for (int i = 0; i < hullPoints.size(); i++) {
         if (toFile)
             ofile << hullPoints[i].toString();
         cout << hullPoints[i].toString();
     }
 }
Referenced by main().
writeOutPoints()
void Set::writeOutPoints (bool toFile = false)
{
     if (toFile)
         ofile << points.size() << endl;
     cout << points.size() << endl;
     for (int i = 0; i < points.size(); i++) {
         if(toFile)
             ofile << points[i].toString();
         cout << points[i].toString();
     }
 }
Referenced by main().
writeOutPrimitives()
void Set::writeOutPrimitives (bool toFile = false)
{
     if (toFile)
         ofile << primitives.size() << endl;
     cout << primitives.size() << endl;
     for (int i = 0; i < primitives.size(); i++) {
         cout << primitives[i]->toString();
         if (toFile)
             ofile << primitives[i]->toString();
     }
 }
Referenced by main().
Member Data Documentation
debugPoint
Point Set::debugPoint static
hullPoints
vector<Point> Set::hullPoints
ofile
ofstream Set::ofile
points
vector<Point> Set::points
primitives
vector<Primitive *> Set::primitives
The documentation for this class was generated from the following files:
G:/GIT/home-assignment-szekely-tibi/ConvexHullOfIntersections/Set.h
G:/GIT/home-assignment-szekely-tibi/ConvexHullOfIntersections/Set.cpp